SET NAMES utf8mb4;
DELETE FROM sys_menu WHERE menu_id IN (2003,2300,2301,2004,2400,2401,2402,2005,2500,2501,2502,2503,2006,2600,2601,2602,2603,2007,2700,2701);
INSERT INTO sys_menu VALUES(2003, '用户管理', '2000', '3', '/news/user', '', 'C', '0', '1', 'news:user:view', 'fa fa-users', 'admin', SYSDATE(), '', NULL, '用户管理菜单');
INSERT INTO sys_menu VALUES(2300, '用户查询', '2003', '1', '#', '', 'F', '0', '1', 'news:user:list', '#', 'admin', SYSDATE(), '', NULL, '');
INSERT INTO sys_menu VALUES(2301, '用户查看', '2003', '2', '#', '', 'F', '0', '1', 'news:user:detail', '#', 'admin', SYSDATE(), '', NULL, '');
INSERT INTO sys_menu VALUES(2004, '评论管理', '2000', '4', '/news/comment', '', 'C', '0', '1', 'news:comment:view', 'fa fa-comments', 'admin', SYSDATE(), '', NULL, '评论管理菜单');
INSERT INTO sys_menu VALUES(2400, '评论查询', '2004', '1', '#', '', 'F', '0', '1', 'news:comment:list', '#', 'admin', SYSDATE(), '', NULL, '');
INSERT INTO sys_menu VALUES(2401, '评论审核', '2004', '2', '#', '', 'F', '0', '1', 'news:comment:audit', '#', 'admin', SYSDATE(), '', NULL, '');
INSERT INTO sys_menu VALUES(2402, '评论删除', '2004', '3', '#', '', 'F', '0', '1', 'news:comment:remove', '#', 'admin', SYSDATE(), '', NULL, '');
INSERT INTO sys_menu VALUES(2005, '频道管理', '2000', '5', '/news/channel', '', 'C', '0', '1', 'news:channel:view', 'fa fa-tv', 'admin', SYSDATE(), '', NULL, '频道管理菜单');
INSERT INTO sys_menu VALUES(2500, '频道查询', '2005', '1', '#', '', 'F', '0', '1', 'news:channel:list', '#', 'admin', SYSDATE(), '', NULL, '');
INSERT INTO sys_menu VALUES(2501, '频道新增', '2005', '2', '#', '', 'F', '0', '1', 'news:channel:add', '#', 'admin', SYSDATE(), '', NULL, '');
INSERT INTO sys_menu VALUES(2502, '频道修改', '2005', '3', '#', '', 'F', '0', '1', 'news:channel:edit', '#', 'admin', SYSDATE(), '', NULL, '');
INSERT INTO sys_menu VALUES(2503, '频道删除', '2005', '4', '#', '', 'F', '0', '1', 'news:channel:remove', '#', 'admin', SYSDATE(), '', NULL, '');
INSERT INTO sys_menu VALUES(2006, '活动管理', '2000', '6', '/news/activity', '', 'C', '0', '1', 'news:activity:view', 'fa fa-calendar', 'admin', SYSDATE(), '', NULL, '活动管理菜单');
INSERT INTO sys_menu VALUES(2600, '活动查询', '2006', '1', '#', '', 'F', '0', '1', 'news:activity:list', '#', 'admin', SYSDATE(), '', NULL, '');
INSERT INTO sys_menu VALUES(2601, '活动新增', '2006', '2', '#', '', 'F', '0', '1', 'news:activity:add', '#', 'admin', SYSDATE(), '', NULL, '');
INSERT INTO sys_menu VALUES(2602, '活动修改', '2006', '3', '#', '', 'F', '0', '1', 'news:activity:edit', '#', 'admin', SYSDATE(), '', NULL, '');
INSERT INTO sys_menu VALUES(2603, '活动删除', '2006', '4', '#', '', 'F', '0', '1', 'news:activity:remove', '#', 'admin', SYSDATE(), '', NULL, '');
INSERT INTO sys_menu VALUES(2007, '举报管理', '2000', '7', '/news/report', '', 'C', '0', '1', 'news:report:view', 'fa fa-flag', 'admin', SYSDATE(), '', NULL, '举报管理菜单');
INSERT INTO sys_menu VALUES(2700, '举报查询', '2007', '1', '#', '', 'F', '0', '1', 'news:report:list', '#', 'admin', SYSDATE(), '', NULL, '');
INSERT INTO sys_menu VALUES(2701, '举报处理', '2007', '2', '#', '', 'F', '0', '1', 'news:report:handle', '#', 'admin', SYSDATE(), '', NULL, '');
SELECT menu_id, menu_name FROM sys_menu WHERE parent_id = 2000 ORDER BY order_num;
